import CategoryHeading from "@/components/sections/CategoryHeading";
import "../globals.css";
import Footer from "@/components/footer/Footer";
export const metadata = {
  title: {
    default: "Cherry Glitz",
    template: "%s - Cherry Glitz | Main Category",
  },
  description:
    "Discover the best beauty parlors, hair salons, massage centers, spas, and tattoo shops in India. From bridal makeup to relaxing massages and unique tattoo designs, find top-rated services near you.",
  keywords: [
    "Best beauty parlor in Mumbai",
    "Best beauty parlor in Delhi",
    "Best beauty parlor in Bangalore",
    "Best beauty parlor in Chennai",
    "Best beauty parlor in Hyderabad",
    "Best beauty parlor in Kolkata",
    "Best beauty parlor in Pune",
    "Women's beauty parlor near me",
    "Bridal makeup parlor",
    "Facial parlor",
    "Skin treatment parlor",
    "Waxing parlor",
    "Manicure pedicure parlor",
    "Best hair salon in Mumbai",
    "Best hair salon in Delhi",
    "Best hair salon in Bangalore",
    "Best hair salon in Chennai",
    "Best hair salon in Hyderabad",
    "Best hair salon in Kolkata",
    "Best hair salon in Pune",
    "Hair cutting salon",
    "Hair coloring salon",
    "Hair straightening salon",
    "Hair styling salon",
    "Hair spa",
    "Hair rebonding salon",
    "Hair extensions salon",
    "Best massage center in Mumbai",
    "Best massage center in Delhi",
    "Best massage center in Bangalore",
    "Best massage center in Chennai",
    "Best massage center in Hyderabad",
    "Best massage center in Kolkata",
    "Best massage center in Pune",
    "Full body massage",
    "Couple massage",
    "Aromatherapy massage",
    "Thai massage",
    "Swedish massage",
    "Deep tissue massage",
    "Head massage",
    "Best spa in Mumbai",
    "Best spa in Delhi",
    "Best spa in Bangalore",
    "Best spa in Chennai",
    "Best spa in Hyderabad",
    "Best spa in Kolkata",
    "Best spa in Pune",
    "Luxury spa",
    "Ayurvedic spa",
    "Wellness spa",
    "Spa packages",
    "Spa treatments",
    "Spa resorts",
    "Best tattoo artist in Mumbai",
    "Best tattoo artist in Delhi",
    "Best tattoo artist in Bangalore",
    "Best tattoo artist in Chennai",
    "Best tattoo artist in Hyderabad",
    "Best tattoo artist in Kolkata",
    "Best tattoo artist in Pune",
    "Tattoo studio",
    "Tattoo designs",
    "Tribal tattoo",
    "3D tattoo",
    "Watercolor tattoo",
    "Temporary tattoo",
    "Tattoo removal",
    "Makeup artist near me",
    "Bridal makeup packages",
    "Facial treatment",
    "Anti-aging facial",
    "Skin whitening treatment",
    "Body polishing",
    "Laser hair removal",
    "Hair cut for women",
    "Hair color trends",
    "Keratin hair treatment",
    "Hair botox",
    "Hair smoothening",
    "Hair volume boost",
    "Haircut for men",
    "Couples massage near me",
    "Pregnancy massage",
    "Sports massage",
    "Lymphatic drainage massage",
    "Reflexology massage",
    "Hot stone massage",
    "Shiatsu massage",
    "Luxury spa packages",
    "Spa retreats",
    "Spa day deals",
    "Spa memberships",
    "Spa gift cards",
    "Spa party",
    "Spa staycation",
    "Tattoo ideas",
    "Small tattoo designs",
    "Minimalist tattoos",
    "Couple tattoos",
    "Meaningful tattoos",
    "Cover up tattoos",
    "Tattoo aftercare",
    "Beauty and wellness services",
    "Salon and spa treatments",
    "Holistic healing",
    "Relaxation and rejuvenation",
    "Pampering experiences",
    "Luxury self-care",
    "Organic and natural products",
    "Vegan and cruelty-free",
    "Best beauty salon",
    "Top rated beauty parlors",
    "Affordable beauty services",
    "Expert makeup artists",
    "Professional hair stylists",
    "Relaxing spa experiences",
    "Therapeutic massages",
    "Unique tattoo designs",
    "Beauty treatment packages",
    "Health and wellness spa",
    "Permanent makeup",
    "Tattoo consultations",
    "Top beauty services",
    "Customized beauty treatments",
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CategoryHeading />
        {children}
        <Footer />
      </body>
    </html>
  );
}
