import CategoryHeading from "@/components/sections/CategoryHeading";
import "../globals.css";
import Footer from "@/components/footer/Footer";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CategoryHeading />
        {children}
        <Footer />
      </body>
    </html>
  );
}
