import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import WomenHeading from "@/components/sections/WomenHeader";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WomenHeading />
        {children}
        <Footer />
        <Toaster position="top-right" theme="light" richColors />
      </body>
    </html>
  );
}
