"use client";
import React from "react";
import CityDropdown from "@/components/sections/CityDropdown";

const delhi = {
  list: [
    "Connaught Place",
    "Karol Bagh",
    "Chandni Chowk",
    "Lajpat Nagar",
    "Hauz Khas",
    "Saket",
    "Dwarka",
    "Rohini",
    "Vasant Kunj",
    "Nehru Place",
    "Mayur Vihar",
    "Pitampura",
    "Rajouri Garden",
    "Greater Kailash",
    "Defence Colony",
    "Paharganj",
    "South Extension",
    "Janakpuri",
    "Noida",
    "Gurgaon",
    "Ghaziabad",
    "Faridabad",
    "Okhla",
    "Shahdara",
    "Patel Nagar",
    "Malviya Nagar",
    "Paschim Vihar",
    "Green Park",
    "Indirapuram",
    "Vasundhara",
    "Uttam Nagar",
    "Vasant Vihar",
    "New Friends Colony",
    "Narela",
    "Sarita Vihar",
    "Kalkaji",
    "Tilak Nagar",
    "Punjabi Bagh",
    "Kirti Nagar",
    "Ashok Vihar",
    "Shahdara",
    "Dilshad Garden",
    "Jamia Nagar",
    "Sarojini Nagar",
    "Model Town",
    "Mehrauli",
    "Jangpura",
    "Rohini",
    "Shahdara",
    "Dwarka",
  ],
  name: "Delhi",
};

const mumbai = {
  list: [
    "Andheri",
    "Bandra",
    "Borivali",
    "Chembur",
    "Colaba",
    "Dadar",
    "Dahisar",
    "Dharavi",
    "Goregaon",
    "Jogeshwari",
    "Juhu",
    "Kandivali",
    "Khar",
    "Malad",
    "Matunga",
    "Mulund",
    "Powai",
    "Santacruz",
    "Sion",
    "Versova",
    "Vile Parle",
    "Wadala",
    "Worli",
    "Lower Parel",
    "Mahim",
    "Marine Lines",
    "Ghatkopar",
    "Byculla",
    "Panvel",
    "Navi Mumbai",
    "Tardeo",
    "Parel",
    "Kurla",
    "Kalbadevi",
    "Fort",
    "Grant Road",
    "Churchgate",
    "Vikhroli",
    "Malabar Hill",
    "Kanjurmarg",
    "Bhayandar",
    "Mira Road",
    "Thane",
    "Vashi",
    "Airoli",
    "Ghodbunder Road",
    "Sanpada",
    "Nerul",
    "Belapur",
    "Kalyan",
  ],
  name: "Mumbai",
};

const Kolkata = {
  areas: [
    "Salt Lake City",
    "Park Street",
    "Howrah",
    "Ballygunge",
    "Alipore",
    "Esplanade",
    "New Town",
    "Dum Dum",
    "Behala",
    "Tollygunge",
    "Rajarhat",
    "Garia",
    "Jadavpur",
    "Sealdah",
    "Barrackpore",
    "Shyambazar",
    "Barasat",
    "Lake Town",
    "Kalighat",
    "Kasba",
    "Dharmatala",
    "Beliaghata",
    "Ultadanga",
    "Jodhpur Park",
    "Baguiati",
    "Santoshpur",
    "Kestopur",
    "Sonarpur",
    "Rajpur-Sonarpur",
    "Narendrapur",
    "Gariahat",
    "Kankurgachi",
    "Maniktala",
    "Salt Lake Sector V",
    "Hatibagan",
    "Baranagar",
    "Park Circus",
    "Metiabruz",
    "Topsia",
    "Haltu",
    "Jadavgarh",
    "Parnasree Pally",
    "Shibpur",
    "Bansdroni",
    "Phoolbagan",
    "Belgachia",
    "Joka",
    "Madhyamgram",
    "Kalikapur",
    "Barisha",
  ],
  name: "Kolkata",
};

const Bangalore = {
  areas: [
    "Koramangala",
    "Indiranagar",
    "Jayanagar",
    "Whitefield",
    "Electronic City",
    "BTM Layout",
    "Marathahalli",
    "HSR Layout (Hosur-Sarjapur Road Layout)",
    "Malleshwaram",
    "Bannerghatta Road",
    "Rajajinagar",
    "JP Nagar (Jayaprakash Nagar)",
    "Hebbal",
    "Yelahanka",
    "Basavanagudi",
    "Basaveshwaranagar",
    "Bellandur",
    "CV Raman Nagar",
    "Banashankari",
    "Kalyan Nagar",
    "KR Puram (Krishnarajapuram)",
    "Vijayanagar",
    "Bommanahalli",
    "Shivajinagar",
    "Domlur",
    "Cox Town",
    "Jeevanbheemanagar",
    "Peenya",
    "Rajarajeshwari Nagar",
    "Sadashivanagar",
    "Sanjaynagar",
    "Banaswadi",
    "Frazer Town",
    "Nagarbhavi",
    "Sahakara Nagar",
    "HBR Layout (Hennur-Banaswadi-Ring Road Layout)",
    "Hosakerehalli",
    "Hulimavu",
    "Thippasandra",
    "Thyagarajanagar",
    "Vidyaranyapura",
    "Koramangala 4th Block",
    "Koramangala 5th Block",
    "Koramangala 6th Block",
    "Koramangala 7th Block",
    "Koramangala 8th Block",
    "Koramangala 1st Block",
    "Koramangala 2nd Block",
    "Koramangala 3rd Block",
    "Malleshwaram West",
  ],
  name: "Bangalore",
};

const Chennai = {
  areas: [
    "Anna Nagar",
    "Thyagaraya Nagar",
    "Velachery",
    "Adyar",
    "Mylapore",
    "Nungambakkam",
    "Tambaram",
    "Teynampet",
    "Kodambakkam",
    "Alwarpet",
    "Saidapet",
    "Ashok Nagar",
    "Guindy",
    "Egmore",
    "Choolaimedu",
    "Triplicane",
    "Pallavaram",
    "Royapettah",
    "Perambur",
    "Kilpauk",
    "Porur",
    "Virugambakkam",
    "Koyambedu",
    "Medavakkam",
    "Madipakkam",
    "Poonamallee",
    "Ambattur",
    "Anna Salai",
    "Saligramam",
    "Thiruvanmiyur",
    "Velachery",
    "Chromepet",
    "Adambakkam",
    "Nanganallur",
    "Perungudi",
    "Thoraipakkam",
    "Kolathur",
    "Mogappair",
    "Vadapalani",
    "Arumbakkam",
    "Mambalam",
    "Besant Nagar",
    "Aminjikarai",
    "Kotturpuram",
    "Royapuram",
    "Tondiarpet",
    "Chetpet",
    "KK Nagar (K. K. Nagar)",
    "Villivakkam",
    "Ekkatuthangal",
  ],
  name: "Chennai",
};

const Hyderabad = {
  areas: [
    "Jubilee Hills",
    "Banjara Hills",
    "Gachibowli",
    "Madhapur",
    "Kukatpally",
    "Hitech City",
    "Secunderabad",
    "Ameerpet",
    "Begumpet",
    "Miyapur",
    "Manikonda",
    "Kondapur",
    "Uppal",
    "Dilsukhnagar",
    "Somajiguda",
    "Himayat Nagar",
    "LB Nagar",
    "Mehdipatnam",
    "Shamshabad",
    "Tarnaka",
    "Attapur",
    "Hafeezpet",
    "Nizampet",
    "Chandanagar",
    "Srinagar Colony",
    "Lingampally",
    "Kothapet",
    "Abids",
    "Nallakunta",
    "Serilingampally",
    "Miyapur",
    "Panjagutta",
    "Koti",
    "Uppal Kalan",
    "Kompally",
    "Bachupally",
    "Vanasthalipuram",
    "Charminar",
    "Karkhana",
    "Bowenpally",
    "Nagole",
    "Sainikpuri",
    "Malkajgiri",
    "Musheerabad",
    "Alwal",
    "Nampally",
    "Boduppal",
    "A.S. Rao Nagar",
    "Barkas",
    "Falaknuma",
  ],
  name: "Hyderabad",
};

const Ahmedabad = {
  areas: [
    "Vastrapur",
    "Satellite",
    "Bopal",
    "Maninagar",
    "Chandkheda",
    "Thaltej",
    "Bodakdev",
    "Naroda",
    "Ghatlodiya",
    "Nikol",
    "Vejalpur",
    "Ranip",
    "Navrangpura",
    "Paldi",
    "Sabarmati",
    "Shahibaug",
    "Usmanpura",
    "Ellis Bridge",
    "Sarkhej",
    "Naranpura",
    "Jodhpur",
    "Memnagar",
    "Gota",
    "Vasna",
    "Gurukul",
    "Ambawadi",
    "Nava Vadaj",
    "Vasna",
    "Ghodasar",
    "Odhav",
    "Science City",
    "Vastral",
    "Shilaj",
    "Motera",
    "Shahpur",
    "Narol",
    "Ambli",
    "Vejalpur",
    "Lambha",
    "Vejalpur",
    "Amraiwadi",
    "Kankaria",
    "Kubernagar",
    "Thakkarbapa Nagar",
    "Jivraj Park",
    "Vasna",
    "Ramol",
    "Dudheshwar",
    "Bhadra",
    "Kalupur",
  ],
  name: "Ahmedabad",
};

const Pune = {
  areas: [
    "Koregaon Park",
    "Kothrud",
    "Aundh",
    "Baner",
    "Hinjewadi",
    "Wakad",
    "Viman Nagar",
    "Magarpatta",
    "Hadapsar",
    "Shivajinagar",
    "Deccan Gymkhana",
    "Camp",
    "Pimpri",
    "Chinchwad",
    "Kalyani Nagar",
    "Chandan Nagar",
    "Karve Nagar",
    "Balewadi",
    "Warje",
    "Katraj",
    "Bavdhan",
    "Dhanori",
    "Wagholi",
    "Bhosari",
    "Yerwada",
    "Kondhwa",
    "Lohegaon",
    "Bibwewadi",
    "Vishrantwadi",
    "Kharadi",
    "Viman Nagar",
    "Narhe",
    "Dhayari",
    "Sanghvi",
    "Sadashiv Peth",
    "Rasta Peth",
    "Kasba Peth",
    "Shaniwar Peth",
    "Sinhagad Road",
    "Swargate",
    "Camp",
    "Erandwane",
    "Wanowrie",
    "Dhole Patil Road",
    "Dhanakwadi",
    "Vishal Nagar",
    "Keshav Nagar",
    "Manjri",
    "Nigdi",
    "Undri",
  ],
  name: "Pune",
};

const Surat = {
  areas: [
    "Adajan",
    "Vesu",
    "Athwa",
    "Piplod",
    "Ghod Dod Road",
    "Varachha",
    "City Light",
    "Katargam",
    "Pal",
    "Parle Point",
    "Udhna",
    "Rander",
    "Nanpura",
    "Dumas",
    "Magdalla",
    "Jahangir Pura",
    "Vesu",
    "Majura Gate",
    "Sagrampura",
    "Sachin",
    "Navsari",
    "Ichchhapor",
    "Hazira",
    "Bardoli",
    "Althan",
    "Palanpur",
    "Amroli",
    "Bhatar",
    "Limbayat",
    "Olpad",
    "Dindoli",
    "Katargam",
    "Rander",
    "Ved Road",
    "Pal Gam",
    "Kadodara",
    "Puna",
    "Pandesara",
    "Kapodra",
    "Athwa Lines",
    "Sachin GIDC",
    "Palsana",
    "Bhimrad",
    "L.P. Savani Road",
    "Dindoli",
    "A.K. Road",
    "Godadara",
    "Mota Varachha",
    "Palanpur Patia",
    "Palanpur Jakatnaka",
  ],
  name: "Surat",
};

const Lucknow = {
  areas: [
    "Gomti Nagar",
    "Hazratganj",
    "Alambagh",
    "Indira Nagar",
    "Aliganj",
    "Vikas Nagar",
    "Mahanagar",
    "Chinhat",
    "Jankipuram",
    "Rajajipuram",
    "Charbagh",
    "Aminabad",
    "Niralanagar",
    "Telibagh",
    "Trans Gomti",
    "Ashiyana",
    "Chowk",
    "Daliganj",
    "Sadar Bazaar",
    "Nishatganj",
    "Kalyanpur",
    "Hussainabad",
    "Thakurganj",
    "Ratan Khand",
    "Vrindavan Colony",
    "Sarojini Nagar",
    "Faizabad Road",
    "Dubagga",
    "Butler Colony",
    "Aashiana",
    "Rajendra Nagar",
    "LDA Colony",
    "Aishbagh",
    "Rajbhawan Colony",
    "Kakori",
    "Mahipatmau",
    "Aryanagar",
    "Gosainganj",
    "Sushant Golf City",
    "Nadwa",
    "Dubagga",
    "Kursi Road",
    "Jiamau",
    "Qaiserbagh",
    "Transport Nagar",
    "Rajajipuram Extension",
    "Gomti Nagar Extension",
    "Alambagh",
    "Raebareli Road",
    "Vikas Nagar Extension",
  ],
  name: "Lucknow",
};

const Jaipur = {
  areas: [
    "Mansarovar",
    "Vaishali Nagar",
    "Malviya Nagar",
    "Jagatpura",
    "Sanganer",
    "Vidhyadhar Nagar",
    "Pratap Nagar",
    "Shyam Nagar",
    "Raja Park",
    "Civil Lines",
    "Ajmer Road",
    "Tonk Road",
    "Bapu Nagar",
    "Nirman Nagar",
    "Adarsh Nagar",
    "Barkat Nagar",
    "Gopalpura",
    "Khatipura",
    "C-Scheme",
    "Lal Kothi",
    "Jhotwara",
    "Murlipura",
    "Chitrakoot",
    "Tilak Nagar",
    "JLN Marg",
    "Gandhi Nagar",
    "Jhotwara Road",
    "Sikar Road",
    "Subhash Nagar",
    "Kalwar Road",
    "Hathroi",
    "Sindhi Camp",
    "New Sanganer Road",
    "Mahesh Nagar",
    "Brahmpuri",
    "Durgapura",
    "Surajpole",
    "Vaishali Circle",
    "Moti Doongri",
    "Shiprapath",
    "Shastri Nagar",
    "Ramganj",
    "Bajaj Nagar",
    "Sanjay Nagar",
    "Shanti Nagar",
    "Malpura",
    "Suraj Nagar East",
    "Suraj Nagar West",
    "Rambagh",
    "Amer",
  ],
  name: "Jaipur",
};

const Kanpur = {
  areas: [
    "Civil Lines",
    "Mall Road",
    "Kakadeo",
    "Swaroop Nagar",
    "Govind Nagar",
    "Shastri Nagar",
    "Barra",
    "Kalyanpur",
    "Birhana Road",
    "Harsh Nagar",
    "Juhi",
    "Fazalganj",
    "Tilak Nagar",
    "Nayaganj",
    "Gumti No. 5",
    "Panki",
    "Yashoda Nagar",
    "Kidwai Nagar",
    "Colonelganj",
    "Azad Nagar",
    "Pandu Nagar",
    "Lal Bangla",
    "Parade",
    "Ratan Lal Nagar",
    "Benajhabar",
    "Gwaltoli",
    "Bithoor",
    "Vikas Nagar",
    "Naubasta",
    "Rawatpur",
    "Vijay Nagar",
    "KDA Colony",
    "Rave 3",
    "Daheli Sujanpur",
    "Tatya Tope Nagar",
    "Gopal Nagar",
    "Lajpat Nagar",
    "Vishnupuri",
    "Jawahar Nagar",
    "P Road",
    "Kanpur Cantonment",
    "Shyam Nagar",
    "Lal Imli",
    "Firozabad",
    "Sharda Nagar",
    "Govindpuri",
    "Swarn Jayanti Vihar",
    "Azad Nagar",
    "Birhana Road",
    "Shyam Nagar",
  ],
  name: "Kanpur",
};

const Indore = {
  areas: [
    "Vijay Nagar",
    "MG Road",
    "South Tukoganj",
    "New Palasia",
    "Old Palasia",
    "Bhawarkua",
    "Sapna Sangeeta",
    "Rau",
    "Navlakha",
    "Rajwada",
    "Khajrana",
    "Khandwa Road",
    "Sudama Nagar",
    "Juni Indore",
    "Nanda Nagar",
    "Pardesipura",
    "Lokmanya Nagar",
    "Kanadia Road",
    "Annapurna",
    "Scheme No. 54",
    "Scheme No. 71",
    "Bengali Square",
    "Rajendra Nagar",
    "Sudama Nagar",
    "Manorama Ganj",
    "Pipaliyahana",
    "Press Complex",
    "Tilak Nagar",
    "Gumasta Nagar",
    "Hatod",
    "Musakhedi",
    "Sukhliya",
    "Bengali Square",
    "Shivaji Nagar",
    "Malwa Mill",
    "Airport Road",
    "Palasia",
    "RNT Marg",
    "Anand Bazaar",
    "Bhanwar Kuwa",
    "Shri Nagar",
    "HIG Colony",
    "MR 10 Road",
    "Raj Mohalla",
    "Kesarbagh Road",
    "Annapurna Road",
    "Juni Indore",
    "Snehlataganj",
    "Machhi Bazar",
    "Anoop Nagar",
  ],
  name: "Indore",
};

const Nagpur = {
  areas: [
    "Dharampeth",
    "Sitabuldi",
    "Sadar",
    "Ramdaspeth",
    "Civil Lines",
    "Dhantoli",
    "Pratap Nagar",
    "Itwari",
    "Laxmi Nagar",
    "Wardhaman Nagar",
    "Ganeshpeth",
    "Shankar Nagar",
    "Nandanvan",
    "Mankapur",
    "Narendra Nagar",
    "Jaripatka",
    "Ajni",
    "Medical Square",
    "Kamptee Road",
    "Manewada",
    "Indora",
    "Trimurti Nagar",
    "Besa",
    "Narsala",
    "Butibori",
    "Gokulpeth",
    "Mahal",
    "Gopal Nagar",
    "Beltarodi",
    "Hingna",
    "Zingabai Takli",
    "Umred Road",
    "Khamla",
    "LAD Square",
    "Bajeria",
    "Ravi Nagar",
    "Khare Town",
    "Hanuman Nagar",
    "Vayusena Nagar",
    "Central Avenue",
    "Deo Nagar",
    "Bhandara Road",
    "Subhash Nagar",
    "Gandhibagh",
    "Rahate Colony",
    "Kachipura",
    "Wardha Road",
    "Friends Colony",
    "Jaripatka",
    "Vayusena Nagar",
  ],
  name: "Nagpur",
};

const Patna = {
  areas: [
    "Patna City",
    "Boring Road",
    "Rajendra Nagar",
    "Kankarbagh",
    "Bailey Road",
    "Anisabad",
    "Dak Bungalow Road",
    "Frazer Road",
    "Exhibition Road",
    "Ashiana Nagar",
    "Phulwari Sharif",
    "Pataliputra Colony",
    "Saguna More",
    "Sheikhpura",
    "Gandhi Maidan",
    "Kurji",
    "Buddha Colony",
    "Raja Bazar",
    "Danapur",
    "Gulzarbagh",
    "Shri Krishna Nagar",
    "Rajiv Nagar",
    "Jakkanpur",
    "Transport Nagar",
    "Kadamkuan",
    "Kidwaipuri",
    "Patliputra Industrial Area",
    "Chiraiyatand",
    "Patliputra Colony",
    "Bankipur",
    "Lodipur",
    "Mahendru",
    "Muradpur",
    "Keshri Nagar",
    "Khagaul",
    "Rukanpura",
    "Digha",
    "Gardanibagh",
    "Nageshwar Colony",
    "Ashok Rajpath",
    "Shivpuri",
    "Kumhrar",
    "Saidpur",
    "Beer Chand Patel Path",
    "Indrapuri",
    "Kumrahar",
    "Phulwari",
    "Salimpur Ahra",
    "Shahganj",
    "Sipara",
  ],
  name: "Patna",
};

const Varanasi = {
  areas: [
    "Sigra",
    "Lanka",
    "Mahmoorganj",
    "Cantonment",
    "Bhelupur",
    "Lahurabir",
    "Ravindrapuri",
    "Shivpur",
    "Kandawa",
    "Orderly Bazar",
    "Nagwa",
    "Gurubagh",
    "Chetganj",
    "Durgakund",
    "Vishwanath Gali",
    "Harhua",
    "Adampura",
    "Katesar",
    "Sundarpur",
    "Varanasi Cantt",
    "Chitaipur",
    "Manduadih",
    "Madanpura",
    "Phulwariya",
    "Paharia",
    "Jaitpura",
    "Orderly Bazaar",
    "Sarai Mohana",
    "Susuwahi",
    "Ashapur",
    "Sarai",
    "Gangapur",
    "Chitaipur",
    "Saraiyan",
    "Khojwan",
    "Khajuri",
    "Luxa",
    "Kamachha",
    "Nagwa Lanka",
    "Siddhagiribagh",
    "Chhittupur",
    "Saket Nagar",
    "Shivdaspur",
    "Sunderpur",
    "Patel Nagar",
    "Vishalakshi Temple Road",
    "Sarnath",
    "Paharia",
    "Lohamandi",
    "Hukulganj",
  ],
  name: "Varanasi",
};

const Kozhikode = {
  areas: [
    "Kozhikode Beach",
    "Mananchira Square",
    "Mavoor Road",
    "Palayam",
    "Kallai",
    "Feroke",
    "Beypore",
    "Nadakkavu",
    "Chevayur",
    "Thondayad",
    "Kuttichira",
    "Kunnamangalam",
    "Pottammal",
    "Kakkodi",
    "Eranhipalam",
    "Malaparamba",
    "Kallai Road",
    "Puthiyara",
    "Vellimadukunnu",
    "Ramanattukara",
    "Elathur",
    "Panniyankara",
    "Meenchanda",
    "Kovoor",
    "Perambra",
    "Koyilandy",
    "Thamarassery",
    "Koduvally",
    "Mukkam",
    "Mankavu",
    "Chevayoor",
    "Mankavu",
    "Cheruvannur",
    "Thiruvannur",
    "Feroke",
    "Khajuri",
    "Luxa",
    "Kamachha",
    "Nagwa Lanka",
    "Siddhagiribagh",
    "Chhittupur",
    "Saket Nagar",
    "Shivdaspur",
    "Sunderpur",
    "Patel Nagar",
    "Vishalakshi Temple Road",
    "Sarnath",
    "Paharia",
    "Lohamandi",
    "Hukulganj",
  ],
  name: "Kozhikode",
};

const Thiruvananthapuram = {
  areas: [
    "Kovalam",
    "Varkala",
    "Poovar",
    "Neyyattinkara",
    "Kazhakkoottam",
    "Attingal",
    "Vizhinjam",
    "Thampanoor",
    "Kowdiar",
    "Poojapura",
    "Peroorkada",
    "Pattom",
    "Palayam",
    "Fort",
    "East Fort",
    "Nalanchira",
    "Sreekariyam",
    "Ambalamukku",
    "Sasthamangalam",
    "Ulloor",
    "Vellayambalam",
    "Mannanthala",
    "Vattiyoorkavu",
    "Kesavadasapuram",
    "Medical College",
    "Karamana",
    "Mudavanmugal",
    "Anayara",
    "Thirumala",
    "Kudappanakunnu",
    "Peroorkada",
    "Nemom",
    "Kaniyapuram",
    "Parassala",
    "Kilimanoor",
    "Khajuri",
    "Luxa",
    "Kamachha",
    "Nagwa Lanka",
    "Siddhagiribagh",
    "Chhittupur",
    "Saket Nagar",
    "Shivdaspur",
    "Sunderpur",
    "Patel Nagar",
    "Vishalakshi Temple Road",
    "Sarnath",
    "Paharia",
    "Lohamandi",
    "Hukulganj",
  ],
  name: "Thiruvananthapuram",
};

const Agra = {
  areas: [
    "Taj Ganj (Taj Mahal)",
    "Fatehabad Road",
    "Sikandra",
    "Sadar Bazaar",
    "Civil Lines",
    "Shahganj",
    "Raja Ki Mandi",
    "Dayal Bagh",
    "Trans Yamuna Colony",
    "Kamla Nagar",
    "Idgah Colony",
    "Nehru Nagar",
    "Sanjay Place",
    "Khandari",
    "Belanganj",
    "Mantola",
    "Lohamandi",
    "Arjun Nagar",
    "Jeoni Mandi",
    "Hariparwat",
    "Pratap Nagar",
    "Tajganj",
    "Shaheed Nagar",
    "Shamsabad",
    "Kheria",
    "Bodla",
    "Kamla Nagar",
    "Nagla Padi",
    "Tajgunj",
    "Baluganj",
    "Taj Nagari",
    "Balkeshwar",
    "Aram Bagh",
    "Taj East Gate Road",
    "Rambagh",
    "Khajuri",
    "Luxa",
    "Kamachha",
    "Nagwa Lanka",
    "Siddhagiribagh",
    "Chhittupur",
    "Saket Nagar",
    "Shivdaspur",
    "Sunderpur",
    "Patel Nagar",
    "Vishalakshi Temple Road",
    "Sarnath",
    "Paharia",
    "Lohamandi",
    "Hukulganj",
  ],
  name: "Agra",
};

const Bhopal = {
  areas: [
    "New Market",
    "MP Nagar (Maharana Pratap Nagar)",
    "Arera Colony",
    "Bairagarh",
    "Shahpura",
    "Habib Ganj",
    "Ayodhya Nagar",
    "Kolar Road",
    "Shyamla Hills",
    "TT Nagar (Tulsi Nagar)",
    "Karond",
    "Misrod",
    "Govindpura",
    "Berasia Road",
    "Nehru Nagar",
    "Bairagarh Kalan",
    "Ayodhya Bypass Road",
    "Barkhedi",
    "Chuna Bhatti",
    "Gandhinagar",
    "Chunabhatti",
    "Katara Hills",
    "Awadhpuri",
    "Mandideep",
    "BHEL Township",
    "Lalghati",
    "Khajuri Kalan",
    "Airport Road",
    "Karari",
    "Raisen Road",
    "Old City",
    "Bhadbhada Road",
    "Hoshangabad Road",
    "Salaiya",
    "Misroad",
    "Khajuri",
    "Luxa",
    "Kamachha",
    "Nagwa Lanka",
    "Siddhagiribagh",
    "Chhittupur",
    "Saket Nagar",
    "Shivdaspur",
    "Sunderpur",
    "Patel Nagar",
    "Vishalakshi Temple Road",
    "Sarnath",
    "Paharia",
    "Lohamandi",
    "Hukulganj",
  ],
  name: "Bhopal",
};

const Coimbatore = {
  areas: [
    "Gandhipuram",
    "Rathinasabapathy Puram",
    "Peelamedu",
    "Saibaba Colony",
    "Vadavalli",
    "Ramanathapuram",
    "Avinashi Road",
    "Ganapathy",
    "Race Course",
    "Singanallur",
    "Thudiyalur",
    "Kavundampalayam",
    "Saravanampatti",
    "Ukkadam",
    "Town Hall",
    "Siddhapudur",
    "Sivananda Colony",
    "Coimbatore Central",
    "Tatabad",
    "Kuniamuthur",
    "Pappanaickenpalayam",
    "Perur",
    "Mettupalayam Road",
    "Vadavalli",
    "Sundarapuram",
    "Ondipudur",
    "Podanur",
    "Vilankurichi",
    "Neelikonampalayam",
    "Kalapatti",
    "Thudialur",
    "Puliakulam",
    "Kuniyamuthur",
    "Vellalore",
    "Sowripalayam",
    "Edayarpalayam",
    "Kurichi",
    "Peelamedu",
    "Thanneer Pandal",
    "Velandipalayam",
    "Kuniamuthur",
    "Kavundampalayam",
    "Saibaba Colony",
    "Singanallur",
    "Thudiyalur",
    "RS Puram",
    "Peelamedu",
    "Avinashi Road",
    "Gandhipuram",
    "Mettupalayam",
  ],
  name: "Coimbatore",
};

const Prayagraj = {
  areas: [
    "Civil Lines",
    "Allahabad University",
    "Kareli",
    "Colonelganj",
    "Georgetown",
    "Katra",
    "Kydganj",
    "Mumfordganj",
    "Rajapur",
    "Chakia",
    "Dandi",
    "Phulpur",
    "Allahapur",
    "Teliyarganj",
    "Jhunsi",
    "Naini",
    "Bahadurganj",
    "Dhoomanganj",
    "Rambagh",
    "Meerapur",
    "Shivkuti",
    "Zero Road",
    "Ashok Nagar",
    "Daraganj",
    "Bamrauli",
    "Attarsuiya",
    "Beli",
    "Bamrauli Airport",
    "Transport Nagar",
    "Mutthiganj",
    "Dhumanganj",
    "Old Katra",
    "Kalindipuram",
    "Mundera",
    "Kalyani Devi",
    "Sulem Sarai",
    "Lukerganj",
    "Phaphamau",
    "Chak",
    "Lakshmipuram",
    "Baghambari Housing Colony",
    "Mumukshu Ashram",
    "Alopi Bagh",
    "Nai Basti",
    "Salori",
    "Rajapur",
    "Shivkuti",
    "Kareli",
    "Kydganj",
    "Colonelganj",
  ],
  name: "Prayagraj",
};

const Kochi = {
  areas: [
    "Fort Kochi",
    "Marine Drive",
    "MG Road (Mahatma Gandhi Road)",
    "Panampilly Nagar",
    "Kakkanad",
    "Edappally",
    "Tripunithura",
    "Thrippunithura",
    "Vyttila",
    "Kadavanthra",
    "Kaloor",
    "Thammanam",
    "Pallimukku",
    "Kalamassery",
    "Aluva",
    "Palarivattom",
    "Ernakulam",
    "Ravipuram",
    "Mattancherry",
    "Kacheripady",
    "Perumbavoor",
    "Angamaly",
    "Chittoor Road",
    "Kadavanthra",
    "Cheranelloor",
    "Kolenchery",
    "Thopumpady",
    "Kundannoor",
    "Kakkanad",
    "Aroor",
    "Varapuzha",
    "Thrikkakara",
    "Alangad",
    "Vazhakkala",
    "Padamughal",
    "Kizhakkambalam",
    "Kumbalam",
    "Vaduthala",
    "Eloor",
    "Kalamassery",
    "Thrikkakara",
    "Palluruthy",
    "Maradu",
    "Poonithura",
    "Muvattupuzha",
    "Vennala",
    "Edappally",
    "Kundannoor",
    "Thoppumpady",
    "Chellanam",
  ],
  name: "Kochi",
};

const Ludhiana = {
  areas: [
    "Model Town",
    "Sarabha Nagar",
    "Civil Lines",
    "Ghumar Mandi",
    "Dugri",
    "Pakhowal Road",
    "Ferozepur Road",
    "Haibowal",
    "Bharat Nagar",
    "Rajguru Nagar",
    "Agar Nagar",
    "Jamalpur",
    "Shaheed Bhagat Singh Nagar",
    "Dhandari Kalan",
    "Salem Tabri",
    "Jawahar Nagar",
    "New Model Town",
    "BRS Nagar",
    "Shimlapuri",
    "Tajpur Road",
    "Bhai Randhir Singh Nagar",
    "Guru Nanak Nagar",
    "Basant Avenue",
    "Sunder Nagar",
    "Gill Road",
    "Field Ganj",
    "Krishna Nagar",
    "Basti Jodhewal",
    "Vishal Nagar",
    "Shaheed Karnail Singh Nagar",
    "Giaspura",
    "Tajpur",
    "Daba Road",
    "Tagore Nagar",
    "Kitchlu Nagar",
    "Rajendra Nagar",
    "Tibba Road",
    "Urban Estate",
    "Industrial Area-A",
    "Janakpuri",
    "Bulara",
    "Transport Nagar",
    "Hambran",
    "Jawaddi Taksal",
    "Gobind Nagar",
    "Civil Lines",
    "Model Town Extension",
    "Guru Arjan Dev Nagar",
    "Focal Point",
    "Kidwai Nagar",
  ],
  name: "Ludhiana",
};

const Vadodara = {
  areas: [
    "Alkapuri",
    "Fatehgunj",
    "Akota",
    "Sayajigunj",
    "Gotri",
    "Subhanpura",
    "Karelibaug",
    "Ellora Park",
    "Race Course Circle",
    "Tarsali",
    "Sama",
    "Gorwa",
    "New VIP Road",
    "Old Padra Road",
    "Waghodia Road",
    "Manjalpur",
    "Vasna Road",
    "Dandia Bazaar",
    "Nizampura",
    "Chhani",
    "Makarpura",
    "Atladara",
    "Kalali",
    "Harni",
    "Karelibaug",
    "Warasiya",
    "Pratapgunj",
    "Diwalipura",
    "Subhanpura",
    "Tandalja",
    "Ellora Park",
    "Chhani Jakat Naka",
    "Mujmahuda",
    "Soma Talav",
    "Harni Road",
    "Vadsar",
    "Dabhoi Road",
    "Ajwa Road",
    "Fatehpura",
    "Navapura",
    "Diwalipura",
    "Akota Stadium",
    "Manjalpur",
    "Gotri Road",
    "Tandalja",
    "Race Course",
    "Waghodia",
    "Karelibaug",
    "Makarpura GIDC",
    "Subhanpura",
  ],
  name: "Vadodara",
};

const Chandigarh = {
  areas: [
    "Sector 17",
    "Sector 22",
    "Sector 35",
    "Sector 9",
    "Sector 26",
    "Sector 11",
    "Sector 34",
    "Sector 16",
    "Sector 15",
    "Sector 8",
    "Sector 20",
    "Sector 18",
    "Sector 7",
    "Sector 21",
    "Sector 27",
    "Sector 10",
    "Sector 33",
    "Sector 32",
    "Sector 30",
    "Sector 19",
    "Sector 28",
    "Sector 31",
    "Sector 36",
    "Sector 23",
    "Sector 24",
    "Sector 29",
    "Sector 37",
    "Sector 38",
    "Sector 39",
    "Sector 40",
    "Sector 41",
    "Sector 42",
    "Sector 43",
    "Sector 44",
    "Sector 45",
    "Sector 46",
    "Sector 47",
    "Sector 48",
    "Sector 49",
    "Sector 50",
    "Sector 51",
    "Sector 52",
    "Sector 53",
    "Sector 54",
    "Sector 55",
    "Sector 56",
    "Sector 57",
    "Sector 58",
    "Sector 59",
    "Sector 60",
  ],
  name: "Chandigarh",
};

const Madurai = {
  areas: [
    "Anna Nagar",
    "Ellis Nagar",
    "Simmakkal",
    "KK Nagar (Kamarajar Salai)",
    "Arasaradi",
    "Alagar Kovil Road",
    "Thiruparankundram",
    "Thirumangalam",
    "Tirunagar",
    "Pasumalai",
    "Melur Road",
    "Tallakulam",
    "Thathaneri",
    "Sellur",
    "Usilampatti",
    "Vilangudi",
    "Koodal Nagar",
    "Sholavandan",
    "Thiruppalai",
    "Anaiyur",
    "Palanganatham",
    "Yagappa Nagar",
    "Pudur",
    "Goripalayam",
    "Thirunagar",
    "Anna Nagar",
    "Sathamangalam",
    "Theni Main Road",
    "Kappalur",
    "Othakadai",
    "Ponnagaram",
    "Gomathipuram",
    "Pasumalai",
    "Surveyor Colony",
    "Alagar Kovil",
    "Periyar",
    "Kalavasal",
    "Bibikulam",
    "Vandiyur",
    "Anuppanadi",
    "Nagamalai",
    "Vaigai Colony",
    "Kamarajar Salai",
    "Thirumohur",
    "Subramaniapuram",
    "Bypass Road",
    "Surya Nagar",
    "Mahalakshmi Nagar",
    "Melakkal",
    "Kochadai",
  ],
  name: "Madurai",
};

const Meerut = {
  areas: [
    "Shastri Nagar",
    "Begum Bridge Road",
    "Meerut Cantonment",
    "Jagriti Vihar",
    "Meerut City",
    "Pallavpuram",
    "Meerut Bypass Road",
    "Modipuram",
    "Mohiuddinpur",
    "Saket",
    "Civil Lines",
    "Ganga Nagar",
    "Brahmpuri",
    "Meerut Kutchery",
    "Meerut University",
    "Hapur Road",
    "Jagriti Vihar",
    "Pallavpuram Phase 1",
    "Kankarkhera",
    "Garh Road",
    "Mangal Pandey Nagar",
    "Shatabdi Nagar",
    "Rohta Road",
    "Sharda Road",
    "Daurala",
    "Partapur",
    "Gokalpur",
    "Sardhana",
    "Lisari Gate",
    "Partapur Industrial Area",
    "Mawana Road",
    "Subharti University",
    "Shyamnagar",
    "Mawana",
    "Modipuram Industrial Area",
    "Rohta Industrial Area",
    "Meerut-Hapur Road",
    "Janakpuri",
    "Kankerkhera Industrial Area",
    "Daurala Sugar Works",
    "Kithore",
    "Kunda",
    "Mohiuddinpur Industrial Area",
    "Partapur Sugar Mill",
    "Ganganagar",
    "Bhawanpur",
    "Hastinapur",
    "Sardhana Road",
    "Mawana Sugar Works",
    "Rohta Sugar Works",
  ],
  name: "Meerut",
};

const Visakhapatnam = {
  areas: [
    "MVP Colony (Madhurawada, Visakhapatnam Port)",
    "Gajuwaka",
    "Seethammadhara",
    "Dwaraka Nagar",
    "Akkayyapalem",
    "NAD Junction (Naval Armament Depot)",
    "Waltair",
    "Siripuram",
    "Asilmetta",
    "Jagadamba Junction",
    "Madhurawada",
    "MVP Double Road",
    "Allipuram",
    "RTC Complex",
    "Gopalapatnam",
    "Kancharapalem",
    "Ram Nagar",
    "Sagar Nagar",
    "Beach Road",
    "Lawsons Bay Colony",
    "Rushikonda",
    "Pedagantyada",
    "Adarsh Nagar",
    "Nad Junction",
    "Pendurthi",
    "Autonagar",
    "Sriharipuram",
    "PM Palem",
    "Muralinagar",
    "Simhachalam",
    "MVP Colony",
    "Gajuwaka",
    "Akkayyapalem",
    "Seethammadhara",
    "Dwaraka Nagar",
    "Siripuram",
    "NAD Junction",
    "Asilmetta",
    "Jagadamba Junction",
    "Madhurawada",
    "Gopalapatnam",
    "Kancharapalem",
    "Ram Nagar",
    "Sagar Nagar",
    "Beach Road",
    "Rushikonda",
    "Pedagantyada",
    "Nad Junction",
    "Pendurthi",
    "Autonagar",
  ],
  name: "Visakhapatnam",
};

const Jamshedpur = {
  areas: [
    "Sakchi",
    "Bistupur",
    "Kadma",
    "Telco Colony",
    "Mango",
    "Sonari",
    "Circuit House Area",
    "Adityapur",
    "Golmuri",
    "Jugsalai",
    "Gamharia",
    "Agrico",
    "Golmuri Cantt",
    "Baridih",
    "Dimna",
    "Tatanagar",
    "Azadnagar",
    "Bhuiyandih",
    "Bhalubasa",
    "Sarjamda",
    "Parsudih",
    "Sidhgora",
    "Burma Mines",
    "Bagbera",
    "Karandih",
    "Baradwari",
    "Agrico Road",
    "Kalimati Road",
    "Jugsalai Road",
    "Golmuri Market Area",
    "New Baradwari",
    "Circuit House Area",
    "Burma Mines",
    "Sonari",
    "Baridih",
    "Bhuiyandih",
    "Golmuri Cantt",
    "Azadnagar",
    "Telco Colony",
    "Sidhgora",
    "Parsudih",
    "Baridih Basti",
    "Sarjamda",
    "Kadma",
    "Bagbera",
    "Karandih",
    "Bistupur",
    "Dimna",
    "Sakchi",
    "Adityapur",
  ],
  name: "Jamshedpur",
};
export default function CityRound() {
  return (
    <div className=" mt-4 flex  w-full flex-col justify-between gap-4">
      <div className="h-8 w-full overflow-hidden rounded-md shadow-md shadow-black/30 ring-2 ring-blue-700/20">
        <div className="inline-flex h-full w-full animate-shimmer flex-row items-center justify-center gap-1  bg-white bg-[linear-gradient(110deg,#ffffff,45%,#ff0000,55%,#ffffff)] bg-[length:200%_100%] ">
          <CityDropdown list={delhi.list} name={delhi.name} />
        </div>
      </div>
    </div>
  );
}
