import { Inter } from "next/font/google";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Explore top-rated beauty parlors, hair salons, massage centers, spas, and tattoo shops across India. Find the best places for bridal makeup, haircuts, full body massages, luxury spa treatments, and unique tattoo designs near you in cities like Mumbai, Delhi, Bangalore, Chennai, Hyderabad, Kolkata, and Pune.",

  keywords: [
    // Keywords for Mumbai
    "Best beauty parlor in Mumbai",
    "Women's beauty parlor near me in Mumbai",
    "Bridal makeup parlor in Mumbai",
    "Facial parlor in Mumbai",
    "Skin treatment parlor in Mumbai",
    "Waxing parlor in Mumbai",
    "Manicure pedicure parlor in Mumbai",
    "Best hair salon in Mumbai",
    "Hair cutting salon in Mumbai",
    "Hair coloring salon in Mumbai",
    "Hair straightening salon in Mumbai",
    "Hair styling salon in Mumbai",
    "Hair spa in Mumbai",
    "Hair rebonding salon in Mumbai",
    "Hair extensions salon in Mumbai",
    "Best massage center in Mumbai",
    "Full body massage in Mumbai",
    "Couple massage in Mumbai",
    "Aromatherapy massage in Mumbai",
    "Thai massage in Mumbai",
    "Swedish massage in Mumbai",
    "Deep tissue massage in Mumbai",
    "Head massage in Mumbai",
    "Best spa in Mumbai",
    "Luxury spa in Mumbai",
    "Ayurvedic spa in Mumbai",
    "Wellness spa in Mumbai",
    "Spa packages in Mumbai",
    "Spa treatments in Mumbai",
    "Spa resorts in Mumbai",
    "Best tattoo artist in Mumbai",
    "Tattoo studio in Mumbai",
    "Tattoo designs in Mumbai",
    "Tribal tattoo in Mumbai",
    "3D tattoo in Mumbai",
    "Watercolor tattoo in Mumbai",
    "Temporary tattoo in Mumbai",
    "Tattoo removal in Mumbai",

    // Keywords for Delhi
    "Best beauty parlor in Delhi",
    "Women's beauty parlor near me in Delhi",
    "Bridal makeup parlor in Delhi",
    "Facial parlor in Delhi",
    "Skin treatment parlor in Delhi",
    "Waxing parlor in Delhi",
    "Manicure pedicure parlor in Delhi",
    "Best hair salon in Delhi",
    "Hair cutting salon in Delhi",
    "Hair coloring salon in Delhi",
    "Hair straightening salon in Delhi",
    "Hair styling salon in Delhi",
    "Hair spa in Delhi",
    "Hair rebonding salon in Delhi",
    "Hair extensions salon in Delhi",
    "Best massage center in Delhi",
    "Full body massage in Delhi",
    "Couple massage in Delhi",
    "Aromatherapy massage in Delhi",
    "Thai massage in Delhi",
    "Swedish massage in Delhi",
    "Deep tissue massage in Delhi",
    "Head massage in Delhi",
    "Best spa in Delhi",
    "Luxury spa in Delhi",
    "Ayurvedic spa in Delhi",
    "Wellness spa in Delhi",
    "Spa packages in Delhi",
    "Spa treatments in Delhi",
    "Spa resorts in Delhi",
    "Best tattoo artist in Delhi",
    "Tattoo studio in Delhi",
    "Tattoo designs in Delhi",
    "Tribal tattoo in Delhi",
    "3D tattoo in Delhi",
    "Watercolor tattoo in Delhi",
    "Temporary tattoo in Delhi",
    "Tattoo removal in Delhi",

    // Keywords for Bangalore
    "Best beauty parlor in Bangalore",
    "Women's beauty parlor near me in Bangalore",
    "Bridal makeup parlor in Bangalore",
    "Facial parlor in Bangalore",
    "Skin treatment parlor in Bangalore",
    "Waxing parlor in Bangalore",
    "Manicure pedicure parlor in Bangalore",
    "Best hair salon in Bangalore",
    "Hair cutting salon in Bangalore",
    "Hair coloring salon in Bangalore",
    "Hair straightening salon in Bangalore",
    "Hair styling salon in Bangalore",
    "Hair spa in Bangalore",
    "Hair rebonding salon in Bangalore",
    "Hair extensions salon in Bangalore",
    "Best massage center in Bangalore",
    "Full body massage in Bangalore",
    "Couple massage in Bangalore",
    "Aromatherapy massage in Bangalore",
    "Thai massage in Bangalore",
    "Swedish massage in Bangalore",
    "Deep tissue massage in Bangalore",
    "Head massage in Bangalore",
    "Best spa in Bangalore",
    "Luxury spa in Bangalore",
    "Ayurvedic spa in Bangalore",
    "Wellness spa in Bangalore",
    "Spa packages in Bangalore",
    "Spa treatments in Bangalore",
    "Spa resorts in Bangalore",
    "Best tattoo artist in Bangalore",
    "Tattoo studio in Bangalore",
    "Tattoo designs in Bangalore",
    "Tribal tattoo in Bangalore",
    "3D tattoo in Bangalore",
    "Watercolor tattoo in Bangalore",
    "Temporary tattoo in Bangalore",
    "Tattoo removal in Bangalore",

    // Keywords for Chennai
    "Best beauty parlor in Chennai",
    "Women's beauty parlor near me in Chennai",
    "Bridal makeup parlor in Chennai",
    "Facial parlor in Chennai",
    "Skin treatment parlor in Chennai",
    "Waxing parlor in Chennai",
    "Manicure pedicure parlor in Chennai",
    "Best hair salon in Chennai",
    "Hair cutting salon in Chennai",
    "Hair coloring salon in Chennai",
    "Hair straightening salon in Chennai",
    "Hair styling salon in Chennai",
    "Hair spa in Chennai",
    "Hair rebonding salon in Chennai",
    "Hair extensions salon in Chennai",
    "Best massage center in Chennai",
    "Full body massage in Chennai",
    "Couple massage in Chennai",
    "Aromatherapy massage in Chennai",
    "Thai massage in Chennai",
    "Swedish massage in Chennai",
    "Deep tissue massage in Chennai",
    "Head massage in Chennai",
    "Best spa in Chennai",
    "Luxury spa in Chennai",
    "Ayurvedic spa in Chennai",
    "Wellness spa in Chennai",
    "Spa packages in Chennai",
    "Spa treatments in Chennai",
    "Spa resorts in Chennai",
    "Best tattoo artist in Chennai",
    "Tattoo studio in Chennai",
    "Tattoo designs in Chennai",
    "Tribal tattoo in Chennai",
    "3D tattoo in Chennai",
    "Watercolor tattoo in Chennai",
    "Temporary tattoo in Chennai",
    "Tattoo removal in Chennai",

    // Keywords for Hyderabad
    "Best beauty parlor in Hyderabad",
    "Women's beauty parlor near me in Hyderabad",
    "Bridal makeup parlor in Hyderabad",
    "Facial parlor in Hyderabad",
    "Skin treatment parlor in Hyderabad",
    "Waxing parlor in Hyderabad",
    "Manicure pedicure parlor in Hyderabad",
    "Best hair salon in Hyderabad",
    "Hair cutting salon in Hyderabad",
    "Hair coloring salon in Hyderabad",
    "Hair straightening salon in Hyderabad",
    "Hair styling salon in Hyderabad",
    "Hair spa in Hyderabad",
    "Hair rebonding salon in Hyderabad",
    "Hair extensions salon in Hyderabad",
    "Best massage center in Hyderabad",
    "Full body massage in Hyderabad",
    "Couple massage in Hyderabad",
    "Aromatherapy massage in Hyderabad",
    "Thai massage in Hyderabad",
    "Swedish massage in Hyderabad",
    "Deep tissue massage in Hyderabad",
    "Head massage in Hyderabad",
    "Best spa in Hyderabad",
    "Luxury spa in Hyderabad",
    "Ayurvedic spa in Hyderabad",
    "Wellness spa in Hyderabad",
    "Spa packages in Hyderabad",
    "Spa treatments in Hyderabad",
    "Spa resorts in Hyderabad",
    "Best tattoo artist in Hyderabad",
    "Tattoo studio in Hyderabad",
    "Tattoo designs in Hyderabad",
    "Tribal tattoo in Hyderabad",
    "3D tattoo in Hyderabad",
    "Watercolor tattoo in Hyderabad",
    "Temporary tattoo in Hyderabad",
    "Tattoo removal in Hyderabad",

    // Keywords for Kolkata
    "Best beauty parlor in Kolkata",
    "Women's beauty parlor near me in Kolkata",
    "Bridal makeup parlor in Kolkata",
    "Facial parlor in Kolkata",
    "Skin treatment parlor in Kolkata",
    "Waxing parlor in Kolkata",
    "Manicure pedicure parlor in Kolkata",
    "Best hair salon in Kolkata",
    "Hair cutting salon in Kolkata",
    "Hair coloring salon in Kolkata",
    "Hair straightening salon in Kolkata",
    "Hair styling salon in Kolkata",
    "Hair spa in Kolkata",
    "Hair rebonding salon in Kolkata",
    "Hair extensions salon in Kolkata",
    "Best massage center in Kolkata",
    "Full body massage in Kolkata",
    "Couple massage in Kolkata",
    "Aromatherapy massage in Kolkata",
    "Thai massage in Kolkata",
    "Swedish massage in Kolkata",
    "Deep tissue massage in Kolkata",
    "Head massage in Kolkata",
    "Best spa in Kolkata",
    "Luxury spa in Kolkata",
    "Ayurvedic spa in Kolkata",
    "Wellness spa in Kolkata",
    "Spa packages in Kolkata",
    "Spa treatments in Kolkata",
    "Spa resorts in Kolkata",
    "Best tattoo artist in Kolkata",
    "Tattoo studio in Kolkata",
    "Tattoo designs in Kolkata",
    "Tribal tattoo in Kolkata",
    "3D tattoo in Kolkata",
    "Watercolor tattoo in Kolkata",
    "Temporary tattoo in Kolkata",
    "Tattoo removal in Kolkata",

    // Keywords for Pune
    "Best beauty parlor in Pune",
    "Women's beauty parlor near me in Pune",
    "Bridal makeup parlor in Pune",
    "Facial parlor in Pune",
    "Skin treatment parlor in Pune",
    "Waxing parlor in Pune",
    "Manicure pedicure parlor in Pune",
    "Best hair salon in Pune",
    "Hair cutting salon in Pune",
    "Hair coloring salon in Pune",
    "Hair straightening salon in Pune",
    "Hair styling salon in Pune",
    "Hair spa in Pune",
    "Hair rebonding salon in Pune",
    "Hair extensions salon in Pune",
    "Best massage center in Pune",
    "Full body massage in Pune",
    "Couple massage in Pune",
    "Aromatherapy massage in Pune",
    "Thai massage in Pune",
    "Swedish massage in Pune",
    "Deep tissue massage in Pune",
    "Head massage in Pune",
    "Best spa in Pune",
    "Luxury spa in Pune",
    "Ayurvedic spa in Pune",
    "Wellness spa in Pune",
    "Spa packages in Pune",
    "Spa treatments in Pune",
    "Spa resorts in Pune",
    "Best tattoo artist in Pune",
    "Tattoo studio in Pune",
    "Tattoo designs in Pune",
    "Tribal tattoo in Pune",
    "3D tattoo in Pune",
    "Watercolor tattoo in Pune",
    "Temporary tattoo in Pune",
    "Tattoo removal in Pune",

    // General keywords
    "Makeup artist near me",
    "Bridal makeup packages",
    "Facial treatment",
    "Anti-aging facial",
    "Skin whitening treatment",
    "Body polishing",
    "Laser hair removal",
    "Hair cut for women",
    "Hair color trends",
    "Keratin hair treatment",
    "Hair botox",
    "Hair smoothening",
    "Hair volume boost",
    "Haircut for men",
    "Couples massage near me",
    "Pregnancy massage",
    "Sports massage",
    "Lymphatic drainage massage",
    "Reflexology massage",
    "Hot stone massage",
    "Shiatsu massage",
    "Luxury spa packages",
    "Spa retreats",
    "Spa day deals",
    "Spa memberships",
    "Spa gift cards",
    "Spa party",
    "Spa staycation",
    "Tattoo ideas",
    "Small tattoo designs",
    "Minimalist tattoos",
    "Couple tattoos",
    "Meaningful tattoos",
    "Cover up tattoos",
    "Tattoo aftercare",
    "Beauty and wellness services",
    "Salon and spa treatments",
    "Holistic healing",
    "Relaxation and rejuvenation",
    "Pampering experiences",
    "Luxury self-care",
    "Organic and natural products",
    "Vegan and cruelty-free",
    "Best beauty salon",
    "Top rated beauty parlors",
    "Affordable beauty services",
    "Expert makeup artists",
    "Professional hair stylists",
    "Relaxing spa experiences",
    "Therapeutic massages",
    "Unique tattoo designs",
    "Beauty treatment packages",
    "Health and wellness spa",
    "Permanent makeup",
    "Tattoo consultations",
    "Top beauty services",
    "Customized beauty treatments",
    "Best beauty parlor in Hyderabad",
    "Waxing parlor in Hyderabad",
    "Hair extensions salon in Hyderabad",
    "Couple massage in Hyderabad",
    "Spa resorts in Hyderabad",
    "Watercolor tattoo in Hyderabad",

    // Kolkata
    "Best beauty parlor in Kolkata",
    "Manicure pedicure parlor in Kolkata",
    "Haircut for men in Kolkata",
    "Aromatherapy massage in Kolkata",
    "Spa treatments in Kolkata",
    "Temporary tattoo in Kolkata",

    // Pune
    "Best beauty parlor in Pune",
    "Bridal makeup packages in Pune",
    "Keratin hair treatment in Pune",
    "Head massage in Pune",
    "Luxury spa in Pune",
    "Tattoo removal in Pune",

    // Ahmedabad
    "Best beauty parlor in Ahmedabad",
    "Makeup artist near me in Ahmedabad",
    "Hair color trends in Ahmedabad",
    "Shiatsu massage in Ahmedabad",
    "Spa day deals in Ahmedabad",
    "Minimalist tattoos in Ahmedabad",

    // Jaipur
    "Best beauty parlor in Jaipur",
    "Anti-aging facial in Jaipur",
    "Hair smoothening in Jaipur",
    "Reflexology massage in Jaipur",
    "Spa retreats in Jaipur",
    "Couple tattoos in Jaipur",

    // Chandigarh
    "Best beauty parlor in Chandigarh",
    "Skin whitening treatment in Chandigarh",
    "Hair volume boost in Chandigarh",
    "Hot stone massage in Chandigarh",
    "Spa memberships in Chandigarh",
    "Cover up tattoos in Chandigarh",

    // Lucknow
    "Best beauty parlor in Lucknow",
    "Body polishing in Lucknow",
    "Hair botox in Lucknow",
    "Lymphatic drainage massage in Lucknow",
    "Spa gift cards in Lucknow",
    "Meaningful tattoos in Lucknow",
  ],

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-gray-200 px-4 py-2">{children}</body>
    </html>
  );
}
