import { Inter } from "next/font/google";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-gray-200 px-4 py-2">{children}</body>
    </html>
  );
}
